BitSet-backed Bloom filter
Callidon/bloom-filters pull request #44
Opened 2021-11-30 22:12 UTC by dleppik

I added BitSet to api.ts's exports for unit test access.  That wasn't my first inclination, but I didn't see a different way to access a class from dist. 

I've tried to follow the style of the rest of the classes, with two exceptions. Class properties in BitSet are not backed by _underscored fields, as the TypeScript Handbook explicitly recommends otherwise. (Adding a backing field can be done without an API change, removing one can require more code changes. Omitting the backing field yields, if anything, slightly more efficient JavaScript.) Second, BitSet is not AutoExportable although it could be. I ultimately decided that because it is a low-level data structure, it is better to have the flexibility and compactness of an explicit serializer/deserializer.

BTW, it turns out the problem creating a pull request before was related to authentication problems on my end. Sorry for the inconvenience!

2021-12-01 10:00 UTC, Callidon requested changes
A pretty good job, congrats 👍 👏 
However, there's still some polishing to do. I've left a first batch of comments ;)

2021-12-01 14:33 UTC, dleppik commented on src/bloom/bit-set.ts
> +        return result
I prefer functional style, but I didn't see many examples in the code base. Also, I tend to avoid reduce in particular because I have yet to find a developer who reads it easily in any language.

Historically, functional approaches are not as optimized in JavaScript as for loops, requiring extra stack overhead for the embedded function. This may have changed in the last several years. Due to the hash function, this is not a bottleneck, so that doesn't currently apply here—even though bitmaps are usually high-performance data types.

I have no great preference one way or the other.

2021-12-01 14:50 UTC, dleppik commented on src/bloom/bit-set.ts
> +    private array: Uint8Array;
Uint8Array (and TypedArray in general) dates back to around the time of HTML5 and has been fully supported on all modern browsers for many years.

If you are specifically supporting IE 9, you will want to use the core-js polyfill. See [Uint8Array Browser compatibility on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray#browser_compatibility).

2021-12-01 19:53 UTC, dleppik commented on test/bloom-filter-test.js
> -      exported._nbHashes.should.equal(filter._nbHashes)
Filter.length was changed to be backed by this._filter.bitCount(), so exported._length no longer exists.

The other line was erroneously removed. Thanks for catching this!

I think it happened in part because my IDE (WebStorm) complained about accessing a private member directly. The test only succeeds because it is JavaScript using the compiled JavaScript. For now I am putting the line back verbatim, but I would be just as happy to add a public accessor for nbHashes.

2021-12-01 19:56 UTC, dleppik commented on test/bloom-filter-test.js
> -        { type: 'BloomFilter', _size: 1, _length: 1, _nbHashes: 2, seed: 1 }
Looks like another mistake. Adding that back in.

2021-12-02 00:00 UTC, dleppik commented on src/bloom/bit-set.ts
> +            base64: encode(this.array)
I chose to call it base64 so that if we choose to support other encodings, e.g. run-length encoding, its type would be explicit. That said, there are other ways to do that, and I agree that it's a bit of an awkward name.

I'll change it to "content".

2021-12-02 02:07 UTC, dleppik commented on src/bloom/bit-set.ts
> +interface BitSetData {
I hope you don't mind if I dodged by inlining the definition. 😀

2021-12-02 02:24 UTC, dleppik commented on src/bloom/bit-set.ts
> +Copyright (c) 2021 David Leppik
I have no problem with assigning copyright, though in that case I'd prefer to add an `@author`.

2021-12-02 02:25 UTC, dleppik commented on src/bloom/bloom-filter.ts
> +   * @param errorRate - The error rate, i.e. 'false positive' rate, targeted by the filter
You can thank JetBrains. 😀

2021-12-02 09:59 UTC, Callidon commented on test/bloom-filter-test.js
> -      exported._nbHashes.should.equal(filter._nbHashes)
👍

2021-12-02 09:59 UTC, Callidon commented on test/bloom-filter-test.js
> -        { type: 'BloomFilter', _size: 1, _length: 1, _nbHashes: 2, seed: 1 }
👍

2021-12-02 10:01 UTC, Callidon approved these changes
Thank you for taking the feedback into account 👍 
On my opinion, it's good for merging. I just need the review of @folkvir on it, and when it's good for him, we will merge your changes, and release a new version soon after.
Thank you again for your contribution!

2021-12-02 15:47 UTC, folkvir commented on test/bloom-filter-test.js
> -      exported._nbHashes.should.equal(filter._nbHashes)
Actually, public accessors is one of the enhancements we need to make for all structures for inheritance and usage reasons of the classes. Feel free to change the visibility of exported attributes to public. But if you choose to, do it for all!

2021-12-02 22:07 UTC, folkvir commented on src/bloom/bit-set.ts
> +Copyright (c) 2021 David Leppik
@author in first place where you put your hands on. 
Then full authorship in top of the file with same licence but your name if the file is all yours.
Then for full contribution, package.json and licence.

2021-12-07 11:31 UTC, folkvir requested changes
Just a few minor changes and good to merge.

2021-12-07 11:31 UTC, folkvir commented on src/bloom/bit-set.ts
> +        this.array = new Uint8Array(Math.ceil(size / bitsPerWord))
Can you set BitsPerWord a class (or instance) variable of BitSet class in case we need to change it? or set by the constructor by default? For now it is readonly and unmodifiable.
`(size: number, bitsPerWord?: number = 8) { ...; this.bitsPerWord = bitsPerWord }` 
If no reason to modify it in the future you can leave it like this.

2021-12-07 11:31 UTC, folkvir commented on src/bloom/bit-set.ts
> +    /** Returns a JSON-encodable object readable by {@link import}. */
```suggestion
    /** 
     * Returns a JSON-encodable object readable by {@link import}. 
     */
```
Can you fix documentation style for all functions/methods? 
This just style, but will match the rest of the documentation style we want to keep.

2021-12-10 01:45 UTC, lovasoa commented on src/bloom/bit-set.ts
> +        this.array[wordIndex] = this.array[wordIndex] | mask
```suggestion
        this.array[wordIndex] |= mask
```

2021-12-10 02:06 UTC, lovasoa requested changes
there is a bug in the remove method

2021-12-10 02:06 UTC, lovasoa commented on src/bloom/bit-set.ts
> +    }
This function doesn't do what it says. It sets the bit to false only if it was set to 1 before, otherwise it switches it to 1.

Maybe you meant

 ```suggestion
    /**
     *  Set the bit to false if it is currently set to true, otherwise it set it to true
     * @param index position of the bit, zero-indexed
     */
    switch(index: number) {
        const wordIndex = Math.floor(index / bitsPerWord)
        const mask = 1 << (index % bitsPerWord)
        this.array[wordIndex] ^= mask
    }
```

or 

```suggestion
    /**
     * Set the bit to false
     * @param index position of the bit, zero-indexed
     */
    remove(index: number) {
        const wordIndex = Math.floor(index / bitsPerWord)
        const mask = ~0 ^ (1 << (index % bitsPerWord))
        this.array[wordIndex] &= mask
    }
```

2021-12-10 02:17 UTC, lovasoa commented on package.json
> +    "base64-arraybuffer": "^1.0.1",
Could we let the users encode the arraybuffers if they need to ?
I understand that dealing with strings may be easier in some cases, but today, the web platform allows dealing with raw binary data in most contexts (network communication, file access, webworker messages), and since the stated goal of this new feature is performance and storage size, could we let the user access the raw data and let them encode it to base64 if they need to ?

2021-12-10 03:34 UTC, dleppik commented on package.json
> +    "base64-arraybuffer": "^1.0.1",
As a long-term goal, I think a binary format is a great idea. However, there is not currently a drop-in solution for converting JavaScript objects into binary. BSON does not support raw binary data, and Protobuf requires a fair amount of schema setup. This gives us a big win quickly, and is not an unreasonable format if we wish to support multiple serialization formats. Other open source formats support both binary & text modes for convenience (e.g. STL 3D model files.)

Base64 is such a common format on the web that [MDN has sample code in its glossary](https://developer.mozilla.org/en-US/docs/Glossary/Base64). The new dependency on base64-arraybuffer is only 8k of code. 

I don't want to require that users learn implementation details in order to serialize efficiently. Just ditching the Base64 encoding would force users to search our objects for TypedArrays in order to serialize them compactly, and then figure out how to deserialize them in a memory-efficient manner. They would also have to figure out what sort of TypedArrays we're using, avoid storing an ArrayBuffer-backed TypedArray twice, and deal with endian issues if they find anything other than a UInt8Array.

A binary format is great, but it's a bigger conversation.

2021-12-10 09:43 UTC, lovasoa commented on package.json
> +    "base64-arraybuffer": "^1.0.1",
I understand what you are saying, but I still feel like it should be done the other way: provide the native implementation now (it's less code), and maybe add the base64 serialization as a usability improvement for those who need it later. Providing the base64 directly blocks the people who need the binary representation, but providing the binary representation still lets the ones who need base64 use it if they need to.

@Callidon what do you think ?

2021-12-10 10:39 UTC, Callidon commented on package.json
> +    "base64-arraybuffer": "^1.0.1",
I side with @dleppik on this one. We want users to be able to use the data structures out of the box, without to handle topics like binary representation. For most basic usages, it's fine.
We could provide another export method/API point to allow users to customize their binary representation, but it's outside of the scope of this PR IMO.

2021-12-10 14:30 UTC, dleppik commented on src/bloom/bit-set.ts
> +    }
Good catch. I'm going to remove this method entirely, since it's not used and not properly tested. The class is only there to support the simple Bloom filter, which is write-only. If we don't use it, I don't want people to use it as sample code.

2021-12-10 15:29 UTC, dleppik commented on package.json
> +    "base64-arraybuffer": "^1.0.1",
@lovasoa, I'm not sure what you mean by the native implementation. TypedArrays break JSON serialization. `JSON.parse(JSON.stringify(new Uint8Array(1)))` yields `{ '0': 0 }`, not a Uint8Array. JavaScript has no native binary format, and we need to store the entire Bloom filter, not just a byte array.

2021-12-10 16:34 UTC, lovasoa commented on package.json
> +    "base64-arraybuffer": "^1.0.1",
Yes, I meant a method that returns an Uint8Array (or an ArrayBuffer) instead of a js object, not a method that returns a js object that contains an Uint8Array. There is no need for json serialization at any point.


@Callidon would you be opened to a new pr once this one is merged that implements that ?

2021-12-10 19:35 UTC, dleppik commented on package.json
> +    "base64-arraybuffer": "^1.0.1",
When you do a fully binary version, there are several libraries you may want to consider. BSON is a solid choice, but it may require some tweaking with TypedArrays. I've had good luck with [Protobuf](https://protobufjs.github.io/protobuf.js/) (Protocol Buffers), although it is definitely not plug-and-play; you need to write a .proto type definition which is geared toward high-volume data transfer. I've never tried [MessagePack](https://msgpack.org), but it may be the strongest contender since their sample JavaScript code serializes a UInt8Array.

2021-12-10 21:32 UTC, lovasoa commented on package.json
> +    "base64-arraybuffer": "^1.0.1",
I don't think we need any library to serialize three integers and a byte array...

2021-12-10 22:38 UTC, lovasoa commented on package.json
> +    "base64-arraybuffer": "^1.0.1",
I don't think we need to include any metadata. We'll have a magic number to identify the format, the few integers we need, then the byte array. We don't need anything more.

2021-12-11 08:56 UTC, Callidon commented on package.json
> +    "base64-arraybuffer": "^1.0.1",
@lovasoa I will not open a PR once this is merged, but I will create an issue to track your suggestion. Thus, if you or someone else want to tackle it, they are free to do it. But for more, this topic is outside the scope of this PT.

2021-12-13 08:49 UTC, folkvir requested changes
Please, all the remaining feedback must be addressed before merging.

2021-12-13 08:49 UTC, folkvir commented on src/bloom/bit-set.ts
> +    has(index: number): boolean {
up! Please use public/protected keywords for the visibility of your functions/methods.

2021-12-14 09:10 UTC, folkvir approved these changes

2021-12-17 08:25 UTC, merged

2021-12-17 08:26 UTC, folkvir commented
Merged, thank you @dleppik  for your work and thank you @lovasoa, @Callidon

2021-12-31 09:10 UTC, lovasoa commented
@Callidon @folkvir : Would it be possible to push a new version with this code to npm ?

2021-12-31 09:19 UTC, folkvir commented
Not until the develop branch will be under review. And this will be the 2.0.X version. Because of breaking changes.

2022-02-06 22:25 UTC, lovasoa commented
Hello everyone :)
  Since 2.0 seems to be taking a long time to land, maybe this could be backported to 1.x ? 
  This is a really useful feature !

2022-02-07 13:54 UTC, folkvir commented
Soon soon! Sorry for the delay. New work, very busy and little time to work. I just miss one additional feature, public keywords on everything to let developers customize everything without forking the library. You can follow the develop branch for news.

2022-02-18 09:47 UTC, Callidon commented
@lovasoa @dleppik Hi 👋 We've finally released the `2.0.0` version of the package, which skips this feature!
Sorry for the wait, I hope this release meets your expectations.