Fix MinHash + Add Scalable BF #28 + Optimize Partitionned BF
Callidon/bloom-filters pull request #53
Opened 2022-03-23 12:48 UTC by folkvir

* Fix MinHash, comparison was wrong due to a unique lodash filter.
* Optimize the Partitionned Bloom Filter with a list of BitSet, import is still doable with the old structure to the new one.
  * Remove the length function
* Add Scalable Bloom Filter #28

A major bump is required.

2022-03-23 12:50 UTC, folkvir commented
@Callidon Any idea to recover the length function from Partitionned Bloom Filter?
The PR is in draft until everything is ok, changelog, documentation, minor changes, etc...

2022-03-25 08:33 UTC, Callidon requested changes
I have some comments and suggested changes, but otherwise it looks great. It will be a nice additions to the library, and fixes some impactful bugs. Good job 👏 👍

2022-03-25 08:33 UTC, Callidon commented on README.md
> +- please, PRs on the develop branch. PRs on the master will be refused without comment.
It's a bit of nitpicking, but I would rephrase to "Please open pull requests on the `develop` branch. Direct contributions to the `master` branch will be refused without comments. Also, each sentence in the enumeration is missing a capital letter in its first word.

2022-03-25 08:33 UTC, Callidon commented on src/bloom/partitioned-bloom-filter.ts
> +          // create a new BitSet from the specified array
I think this comment should go around line 126, as it is about the `else` case of the condition

2022-03-25 08:33 UTC, Callidon commented on src/bloom/scalable-bloom-filter.ts
> +'use strict'
Since we switched to typescript, I'm not sure we need to redeclare the strict mode for each file (old habits die hard), and we can just toggle it as a global setting in the typescript compiler options.

2022-03-25 08:33 UTC, Callidon commented on src/bloom/scalable-bloom-filter.ts
> +  public static _s = 2
I suppose you named it `_s` because the algorithm also uses this name. If so, it's fine, I prefer that the code stick as much as possible to the original algorithms. Otherwise, I think we should aim for a more explicit name.

2022-03-25 08:33 UTC, Callidon commented on src/bloom/scalable-bloom-filter.ts
> +      filters.map(filter => filter.saveAsJSON()), // eslint-disable-line @typescript-eslint/no-unsafe-return
Another reminder that our export/import system barely works 😄 But it's not the subject here, it's fine for me.

2022-03-25 08:33 UTC, Callidon commented on src/bloom/scalable-bloom-filter.ts
> +  public set seed(seed: number) {
Can't we move this logic in a super class or a mixin? It seems common to all structures. Same goes for the getter btw.

2022-03-25 08:33 UTC, Callidon commented on src/bloom/scalable-bloom-filter.ts
> +    return found
I think the following is more compact and strictly equivalent
```suggestion
    return this._filters.some((filter) => filter.has(element))
```

2022-03-25 08:33 UTC, Callidon commented on src/bloom/scalable-bloom-filter.ts
> +    }
Why not merge all conditions in the same if, as they all leads to the same return value?
```suggestion
    // assert the seed, the ratio and the capacity are equals
    if (this.seed !== filter.seed || this._ratio !== filter._ratio || this.capacity() !== filter.capacity()) {
      return false
    }
```

2022-03-25 08:33 UTC, Callidon commented on src/sketch/min-hash.ts
> +      // so we compute an itrative minmium
typos
```suggestion
      // so we compute an iterative minimum
```

2022-03-25 13:45 UTC, folkvir commented on src/bloom/scalable-bloom-filter.ts
> +'use strict'
Strict checking is already enable in the tsconfig and tests are ok without `'use strict'`. I will remove the line everywhere!

2022-03-25 15:38 UTC, folkvir commented on src/bloom/scalable-bloom-filter.ts
> +      filters.map(filter => filter.saveAsJSON()), // eslint-disable-line @typescript-eslint/no-unsafe-return
Yes it should auto export based on the type, could be:
1) object or primitive type => check the class
2) array/iterator => iterate and go to 1)

2022-03-25 15:38 UTC, folkvir commented on src/bloom/scalable-bloom-filter.ts
> +  public static _s = 2
Yes, it is according to the paper the same variable. By default with this setting we will follow a power of 2. Changing `_s` to N will follow a power of N. There is no reason to change this settings for now, this is why the variable is _static but not readonly.

2022-03-25 18:01 UTC, folkvir commented on src/bloom/scalable-bloom-filter.ts
> +    return found
`.some` iterates only on a fixed array and do not iterate on inserted elements after the iteration begins while the `while` loop does allow it. For mono-threaded environment your suggestion is ok. +1

2022-03-25 18:05 UTC, folkvir commented on src/bloom/scalable-bloom-filter.ts
> +    }
And yours is less expensive too.

2022-03-25 18:18 UTC, folkvir commented on src/bloom/scalable-bloom-filter.ts
> +  public set seed(seed: number) {
Logic is already in the base filter class we already extend : https://github.com/Callidon/bloom-filters/blob/f580c3caa30bb74338aaae2110fcdb76e6f25a49/src/base-filter.ts#L59-L64

But sometimes, the seed has to be propagated and it is the only way to override it correctly for the Scalable BF

2022-03-25 18:20 UTC, folkvir commented on src/bloom/scalable-bloom-filter.ts
> +'use strict'
commit [9332523](https://github.com/Callidon/bloom-filters/pull/53/commits/93325239aacf3b3bbd613bb7babacba9a0418fcd)

2022-03-25 18:28 UTC, folkvir commented on README.md
> +- please, PRs on the develop branch. PRs on the master will be refused without comment.
commit [ef6c6f3](https://github.com/Callidon/bloom-filters/pull/53/commits/ef6c6f381c8dcee1cc6e3aa236ffb09969b18839)

2022-03-25 18:37 UTC, folkvir commented on src/bloom/partitioned-bloom-filter.ts
> +          // create a new BitSet from the specified array
documentation updated in [b7e8fa5](https://github.com/Callidon/bloom-filters/pull/53/commits/b7e8fa56b86b4008607281b8a5957ade1aa7e0a7)

2022-03-26 07:31 UTC, Callidon approved these changes
Thank for the changes, all is good for me, we can merge it alongside #54 for the next release

2022-03-26 13:23 UTC, merged